// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Population.Infraestructure.Contracts.Entities
{
    public partial class CountryInfoEntity
    {
        public int Id { get; set; }
        public int? CountryId { get; set; }
        public int Year { get; set; }
        public int Population { get; set; }

        public virtual CountryEntity Country { get; set; }
    }
}