// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Population.Infraestructure.Contracts.Entities
{
    public partial class CountryEntity
    {
        public CountryEntity()
        {
            CountryInfos = new HashSet<CountryInfoEntity>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<CountryInfoEntity> CountryInfos { get; set; }
    }
}