// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Universities.Infraestructure.Contracts.DBEntities
{
    public partial class DBUniversityEntity
    {
        public DBUniversityEntity()
        {
            Domains = new HashSet<DBDomainEntity>();
            Webs = new HashSet<DBWebEntity>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Alpha { get; set; }
        public string Province { get; set; }
        public string Country { get; set; }
        public int Deleted { get; set; }

        public virtual ICollection<DBDomainEntity> Domains { get; set; }
        public virtual ICollection<DBWebEntity> Webs { get; set; }
    }
}