// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Universities.Infraestructure.Contracts.DBEntities
{
    public partial class DBWebEntity
    {
        public int Id { get; set; }
        public int? UniversityProperty { get; set; }
        public string Web1 { get; set; }

        public virtual DBUniversityEntity UniversityPropertyNavigation { get; set; }
    }
}